method: random
metric:
  name: test/accuracy
  goal: maximize
parameters:
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.01
  batch_size:
    values: [32, 128]
  epochs:
    value: 10
  pretrained:
    value: True

